# Generated by Django 3.2.10 on 2024-01-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='combine_order_id',
            field=models.CharField(blank=True, max_length=526, null=True),
        ),
        migrations.CreateModel(
            name='OrderBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bank', 'Bank')], default=None, max_length=1024, null=True)),
                ('delivery_charge', models.IntegerField(default=0)),
                ('single_product_price', models.IntegerField(default=0)),
                ('total_billed', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_bill_order', to='product.order')),
            ],
            options={
                'db_table': 'order_bill',
            },
        ),
    ]
